# This workflow checks the links in plaintext and HTML files
name: Check Links

on:
  # Uncomment the 'pull_request' line below to trigger the workflow in PR
  # pull_request:
  # Schedule runs on 12 noon every Sunday
  schedule:
    - cron: '0 12 * * 0'

jobs:
  check_links:
    name: Check Links
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2.3.4
      with:
        path: repository

    - name: Checkout the website
      uses: actions/checkout@v2.3.4
      with:
        ref: gh-pages
        path: website

    - name: Link Checker
      uses: lycheeverse/lychee-action@v1.0.6
      with:
        # 429: Too many requests
        args: >
          --accept 429
          --exclude "*/n$"
          --exclude "*/n#$"
          --exclude "^https://git-scm.com/downloads/u%7Bff0c%7D/u%7B4e0b%7D/u%7B8f7d%7D/u%7B5e76%7D/u%7B5b89%7D/u%7B88c5%7D$"
          --exclude "^https://seismo-learn.org/seismology101/n/n/n/u%7B5e26%7D/u%7B8d85%7D/u%7B94fe%7D/u%7B63a5%7D/u%7B7684%7D/u%7B6587%7D/u%7B5b57%7D/u%7Bff1a%7D$"
          --exclude "https://github.com/seismology-freshman/seismology101"
          --exclude "https://github.com/seismology-freshman/seismology101.git"
          --exclude "seismo-learn@gmail.com"
          --verbose
          "repository/README.md"
          "website/**/*.html"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Issue From File
      uses: peter-evans/create-issue-from-file@v2.3.2
      with:
        title: Link Checker Report
        content-filepath: ./lychee/out.md
